### PR TITLE
added camera driver and simple face detector

### PR DESCRIPTION
**Pull request by yantrabuddhi**

### CODE REVIEW

**Comment by linas** [comment]
Two questions:

1) why are you checking in source code from other ROS packages?

2) why not use pi_vision, which we already support and use in other places?

**Comment by yantrabuddhi** [comment]
Hi Linas,
1) There are minor changes to them specific to our needs and I wanted
them(packages required for this itf project) to all be in a place in a
hierarchy,  i do not understand git that well and get confused about the
right way to make packages put under new hierarchy I want, without loosing
the previous commit info. I know its not the right way to do things, it is
just I have to get lot of things put together in short time by myself and
this avoids things being messed up and saving me time and confusion. [ I
would certainly do the things right way afterwards if i can]. I have tested
all these packages to work before uploading them and would also be like to
be sure i use the correct set of things(i think with git we can freeze
particular versions?)
2) We had used pi vision before and it was more meant for being used with a
depth camera like kinect for good performance, it had terrible performance
without depth information along lot of false positives and does not give us
the advantages we get under a new planned system. The new plan is to use a
face detection that we know works with low false positive[not to be used
for tracking, just detection], can efficiently detect multiple faces in
scene without special camera. Then we pass the face bounding box position
to a nice general tracking system like openTLD(track learn detect). Same
follows for object recognition we have, now we can switch what to track
based on owyl tree decision also based on speech to text. If we can achieve
basic  functions with more efficiency and low false positives then it will
be easier to build better and more predictable capabilities on top of
these.

Those are my reasons, i might not have made the best choices but I am doing
it this way because I think that we can have good results in this way
Regards,
Mandeep

**Comment by linas** [comment]
Ah,

well, for 1) I think it is always bet to contact the original author/maintainer of the code, and ask them to include your changes.  That way, you benefit from any future changes or bug fixes that they make, and they benefit from the changes and fixes that you make.   Right now, by copying in some un-known version of teh code, and making unknown, undocumented changes to it, it becomes impossible to figure out how to move forward. What happens when a new version of the camer driver, or the face detector comes out? How do you port your old changes to the new version?  For this reason, it is best if you send your changes to the lead maintainer or project, and ask them to accept your changes. That way, they become permanent.

2) face detection, but not face tracking .. interesting.  Yes, pi_vision is in some ways terrible.  However, if you are serious about starting a face-detection and tracking project, you should not put the code into the robosapian project. You should start a completely new project, for just that part only.  That way, everyone could use it, not just robosapian.

**Comment by yantrabuddhi** [comment]
Yes, You are right about 1 and 2. I will do it that way soon. Thanks for
looking into it and giving me the advice, that is the better way to go
about it.
Regards,
Mandeep

**Pull request merged**
